import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import ITimeEntry from '../models/ITimeEntry'
import TimeEntryCard from '../components/timeEntryCard'

export async function getServerSideProps(context) {
  return {
    props: {
      // props for your component
    }
  }
}

// async function fetcher<T>(input: RequestInfo) {
//     var response = await fetch(input)
//     return response.json() as Promise<T>
// }

// async function fetcher<T>(input: RequestInfo) {
//     const response = await fetch(input)
//     return await (response.json() as Promise<T>)
// }

export default function Home() : JSX.Element {

  const fetcher = (input: RequestInfo) => fetch(input).then(res => res.json())

  const { data, error } = useSWR("http://localhost:5000/timeEntries", fetcher)

  if (error || !(data as ITimeEntry[])) return <div>failed to load</div>
  if (!data) return <div>loading...</div>

  console.log(data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to TimeTracker!
        </h1>

        {/* {data.map(timeEntry => <TimeEntryCard timeEntry={timeEntry}/>)} */}

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <ul>
            {data.map(timeEntry => <li className={styles.card} key={timeEntry.id}><TimeEntryCard timeEntry={timeEntry}/></li>)}
          </ul>


          {/* <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
